<a href="https://colab.research.google.com/github/gustavocostamiguel/Python_IA/blob/main/NaiveBayes.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [13]:
# Importa a biblioteca pandas para manipulação de dados em DataFrames.
import pandas as pd
# Importa a biblioteca numpy para operações numéricas, especialmente com arrays.
import numpy as np
# Importa train_test_split para dividir os dados em conjuntos de treino e teste.
from sklearn.model_selection import train_test_split
# Importa GaussianNB, o classificador Naive Bayes Gaussiano.
from sklearn.naive_bayes import GaussianNB
# Importa LabelEncoder para codificar rótulos categóricos em numéricos.
from sklearn.preprocessing import LabelEncoder
# Importa métricas de avaliação do modelo, como acurácia, precisão, recall, f1-score e relatório de classificação.
from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score, classification_report
# Importa ConfusionMatrix para visualização da matriz de confusão.
from yellowbrick.classifier import ConfusionMatrix

In [14]:
# Importa a biblioteca pandas para manipulação de dados em DataFrames.
import pandas as pd
# Carrega o arquivo CSV 'insurance.csv' em um DataFrame pandas, mantendo valores 'NA' como estão (sem converter para NaN).
base = pd.read_csv("insurance.csv",keep_default_na=False)
# Exibe as primeiras 5 linhas do DataFrame para uma visualização inicial dos dados.
base.head()

   Unnamed: 0  GoodStudent         Age  ... Airbag   ILiCost DrivHist
0           1        False       Adult  ...  False  Thousand     Many
1           2        False      Senior  ...   True  Thousand     Zero
2           3        False      Senior  ...   True  Thousand      One
3           4        False  Adolescent  ...  False  Thousand     Zero
4           5        False  Adolescent  ...  False  Thousand     Many

[5 rows x 28 columns]

In [15]:
# Remove a coluna 'Unnamed: 0' do DataFrame 'base', pois geralmente é um índice extra indesejado do CSV.
base = base.drop(columns=['Unnamed: 0'])
# Exibe as primeiras 5 linhas do DataFrame novamente para verificar se a coluna foi removida com sucesso.
base.head()

   GoodStudent         Age    SocioEcon  ... Airbag   ILiCost DrivHist
0        False       Adult        Prole  ...  False  Thousand     Many
1        False      Senior        Prole  ...   True  Thousand     Zero
2        False      Senior  UpperMiddle  ...   True  Thousand      One
3        False  Adolescent       Middle  ...  False  Thousand     Zero
4        False  Adolescent        Prole  ...  False  Thousand     Many

[5 rows x 27 columns]

In [16]:
# Exibe o formato (número de linhas e colunas) do DataFrame 'base'.
base.shape

(20000, 27)

In [17]:
# Imprime a contagem de valores nulos para cada coluna no DataFrame 'base'.
print(base.isnull().sum())

GoodStudent     0
Age             0
SocioEcon       0
RiskAversion    0
VehicleYear     0
ThisCarDam      0
RuggedAuto      0
Accident        0
MakeModel       0
DrivQuality     0
Mileage         0
Antilock        0
DrivingSkill    0
SeniorTrain     0
ThisCarCost     0
Theft           0
CarValue        0
HomeBase        0
AntiTheft       0
PropCost        0
OtherCarCost    0
OtherCar        0
MedCost         0
Cushioning      0
Airbag          0
ILiCost         0
DrivHist        0
dtype: int64

In [18]:
# Seleciona a 8ª coluna (índice 7) do DataFrame 'base' como a variável alvo (y) e converte para array numpy.
y = base.iloc[:,7].values
# Remove a 8ª coluna (índice 7) do DataFrame 'base' e seleciona as colunas restantes como as variáveis preditoras (x), convertendo para array numpy.
x = base.drop(base.columns[7], axis=1).values
# Exibe as primeiras linhas do array 'x' para verificar os dados das variáveis preditoras.
x

array([[False, 'Adult', 'Prole', ..., False, 'Thousand', 'Many'],
       [False, 'Senior', 'Prole', ..., True, 'Thousand', 'Zero'],
       [False, 'Senior', 'UpperMiddle', ..., True, 'Thousand', 'One'],
       ...,
       [False, 'Senior', 'UpperMiddle', ..., True, 'Thousand', 'Zero'],
       [False, 'Adult', 'Middle', ..., True, 'Thousand', 'Zero'],
       [False, 'Adult', 'Middle', ..., True, 'Thousand', 'Zero']],
      dtype=object)